version: 2

models:
  - name: England
    description: Displays the locations from England
    columns:
      - name: Country
        data_tests:
          - not_null
      - name: Longitude
        data_tests:
          - not_null 
      - name: Latitude
        data_tests:
          - not_null
  - name: Scotland
    description: Displays the locations from Scotland
    columns:
      - name: Country
        data_tests:
          - not_null
      - name: Longitude
        data_tests:
          - not_null 
      - name: Latitude
        data_tests:
          - not_null
  - name: Wales
    description: Displays the locations from Wales
    columns:
      - name: Country
        data_tests:
          - not_null
      - name: Longitude
        data_tests:
          - not_null 
      - name: Latitude
        data_tests:
          - not_null
  - name: STG_Great_Britain_OpenNames
    description: Collection of locations from the countries in Great Britain
    columns:
      - name: Country
        data_tests:
          - not_null
      - name: Geography
        data_tests:
          - not_null 